import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Image from "next/image";
import {Urbanist} from '@next/font/google'
import BriefCard from "@/components/BriefCard";

const urbanist = Urbanist({display:'swap',variable:'--font-urbanist',subsets:['latin']})

const Briefs = [
  {
    title: "Johnson's Pet Store",
    description: "Our current website is outdated and does not reflect the high-quality products and services that we offer. We want a new website that is user-friendly and showcases our products and services.",
    industry: "Retail Business"
  },
  {
    title: "Johnson's Pet Store",
    description: "Our current website is outdated and does not reflect the high-quality products and services that we offer. We want a new website that is user-friendly and showcases our products and services.",
    industry: "Retail Business"
  },
  {
    title: "Johnson's Pet Store",
    description: "Our current website is outdated and does not reflect the high-quality products and services that we offer. We want a new website that is user-friendly and showcases our products and services.",
    industry: "Retail Business"
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>neobrief - Design Briefs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${urbanist.variable}`}>
        <main className="px-6 lg:px-32 py-2 font-urbanist">
        <Navbar />
        <Hero />
        <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2 lg:gap-10 justify-evenly items-start">
            {Briefs && Briefs.map(brief => {
              return (
                <BriefCard brief={brief} />
              )
            })}
        </section>
        </main>
        
      </main>
    </>
  );
}
